### PR TITLE
Improve the construction of `QobjEvo`

### LINKED ISSUE #338: Solving problems with time-dependent Hamiltonians
### Describe the Issue!

Hi, I am trying to solve a problem with a time-dependent Hamiltonian using QuantumToolbox.jl and sesolve(). My Julia version is 1.11.2

Here is the simplest example of my code:

Screen Shot 2024-12-08 at 1 07 56 AM

When I run this I get the following error:

Screen Shot 2024-12-08 at 1 09 07 AM

I believe the error is caused because H is a tuple but the sesolve() function is expecting it to be a quantum object type. Here are the types of the relevant things in my code:

**julia> typeof(H)
Tuple{QuantumObject{SparseMatrixCSC{ComplexF64, Int64}, OperatorQuantumObject}, typeof(C1_coeff)}**

**julia> typeof(C1_coeff)
typeof(C1_coeff) (singleton type of function C1_coeff, subtype of Function)**

**julia> typeof(H1)
QuantumObject{SparseMatrixCSC{ComplexF64, Int64}, OperatorQuantumObjec**t}

As you can see my H is a tuple of operator-function pairs and when I look at the documentation for sesolve() online it says the Hamiltonian can be of this tuple type:

**`H`: Hamiltonian of the system ``\hat{H}``. It can be either a [`QuantumObject`](@ref), a [`QuantumObjectEvolution`](@ref), or a `Tuple` of operator-function pairs.**

So since my H is a tuple of operator-function pairs I shouldn't be getting an error...right? 

I am hoping that someone here can help me solve this issue. 

Thanks!

### PR DESCRIPTION
**Pull request by ytdHuang**
## Checklist
Thank you for contributing to `QuantumToolbox.jl`! Please make sure you have finished the following tasks before opening the PR.

- [x] Please read [Contributing to QuantumToolbox.jl](https://qutip.org/QuantumToolbox.jl/stable/resources/contributing).
- [x] Any code changes were done in a way that does not break public API.
- [x] Appropriate tests were added and tested locally by running: `make test`.
- [x] Any code changes should be `julia` formatted by running: `make format`.
- [x] All documents (in `docs/` folder) related to code changes were updated and able to build locally by running: `make docs`.
- [x] (If necessary) the `CHANGELOG.md` should be updated (regarding to the code changes) and built by running: `make changelog`.

Request for a review after you have completed all the tasks. If you have not finished them all, you can also open a [Draft Pull Request](https://github.blog/2019-02-14-introducing-draft-pull-requests/) to let the others know this on-going work.

## Description
Summary of this PR:
- add new methods to generate `QobjEvo` with input type `Tuple{QuantumObject,Function}`.
- add argument checks for each coefficient `Function` by using `Base.methods`.

## Related issues or PRs
close #338

### CODE REVIEW

**Comment by ytdHuang** [comment]
Hmm...

the code-quality test succeed in my local laptop...

Not sure why it fails in CI pipeline

**Comment by albertomercurio** [comment]
I think it's good. Do we have tests for type instabilities? What happens if we run

```julia
@inferred QobjEvo((op, coef))
```

and all the other methods?

**Comment by ytdHuang** [comment]
> I think it's good. Do we have tests for type instabilities? What happens if we run
> 
> ```julia
> @inferred QobjEvo((op, coef))
> ```
> 
> and all the other methods?

Ok, added~

**Comment by albertomercurio** [comment]
Are you using the latest versions in your local runtests for the code quality?

**Comment by ytdHuang** [comment]
> Are you using the latest versions in your local runtests for the code quality?

Yes `JET v0.9.12` on MacOS m-series chip

**Comment by albertomercurio** [comment]
I have the same error locally

**Comment by albertomercurio** [comment]
I think the error comes from the new method definition of `QuantumObjectEvolution` and the Julia version `v1.11.2`. Either removing the error, or running with Julia `v1.10.7` doesn't show the error. But still we need to know why.

**Comment by ytdHuang** [comment]
Ok, fixed

**Review by albertomercurio — APPROVED** [review]

**Pull request merged**
