### PR TITLE
ODE-stationary-state solver

### LINKED ISSUE #84: ODE-based `steadystate` solving method
The current existing [`steadystate`](https://github.com/albertomercurio/QuantumToolbox.jl/blob/d04d1da461982ec42324bdf5a16001928eab49b5/src/time_evolution/time_evolution.jl#L254) solving methods doesn't depend on the initial condition (state), but there are some cases which leads to different stationary states because of the initial states.

By the [`multiple-dispatch`](https://docs.julialang.org/en/v1/manual/methods/) feature of `Julia`, we can have a new `steadystate` method with a given initial state.
The stationary state can be obtained based on [`DiffEqCallbacks.jl`](https://docs.sciml.ai/DiffEqCallbacks/stable/) and the solvers in [`OrdinaryDiffEq.jl`](https://github.com/SciML/OrdinaryDiffEq.jl).

For the terminate condition of finding the stationary state, it would be better to use: 

either the following condition is `true`
$$\lVert\frac{\partial |\rho\rangle\rangle}{\partial t}\rVert \leq \textrm{reltol} \times\lVert\frac{\partial |\rho\rangle\rangle}{\partial t}+|\rho\rangle\rangle\rVert$$

or

$$\lVert\frac{\partial |\rho\rangle\rangle}{\partial t}\rVert \leq \textrm{abstol}$$

### PR DESCRIPTION
**Pull request by ilkclord**
close #84

### CODE REVIEW

**Comment by ytdHuang** [comment]
You need to format your code by running the following command:

```
julia -e "using JuliaFormatter; format(".")"
```

**Comment by ilkclord** [comment]
@albertomercurio @ytdHuang 

Could you review this PR when you have time ? Thank you.

**Comment by ytdHuang** [comment]
I have approved it. 

But maybe wait @albertomercurio and see what he says. He is in charge of the UnitaryHack 2024 event in our develop team.

Maybe there is something else needed to be addressed before merging.

**Comment by albertomercurio** [comment]
I think this is great. Thank you very much!

**Comment by albertomercurio** [comment]
Could you comment in #84? Otherwise I can8t assign you to the issue. This is needed for UnitaryHACK?

**Review by albertomercurio — APPROVED** [review]

**Comment by ilkclord** [comment]
@albertomercurio 
I've comment the issue#84

**Pull request merged**
